import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import React from "react";
import { Providers } from "@/components/shared";

const golosText = Golos_Text({
  variable: "--font-golos-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "MelodyMind",
  //   TODO: description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo.png" />
        <title></title>
      </head>
      <body className={`${golosText.variable} antialiased scrollbar`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
